add freeboard delete/modify actions and add option modal in article
wanna-go-home/lens_review_android pull request #37
Opened 2020-12-14 10:32 UTC by up0617

resolve wanna-go-home/Issue#23

생각해보니까 깊이 알려준 Shared View Model로 안해서 재사용불가;; 
코멘트 CRUD하면서 재사용해야해서 그때 하겠음 
@rlarlvy153 deleteSuccess => finish() 왜 안 돼는지 좀 바주셈 ㅠ

2020-12-14 11:19 UTC, rlarlvy153 approved these changes

2020-12-14 11:20 UTC, rlarlvy153 requested changes

2020-12-14 11:20 UTC, rlarlvy153 commented on app/src/main/java/com/wannagohome/lens_review_android/ui/board/article/MoreDialog.kt
> +    private val articleViewModel: ArticleViewModel by viewModel()
private val articleViewModel: ArticleViewModel by viewModel()
-> 
private val articleViewModel: ArticleViewModel by sharedViewModel()

하면 finish 될것임

2020-12-14 12:43 UTC, up0617 commented on app/src/main/java/com/wannagohome/lens_review_android/ui/board/article/MoreDialog.kt
> +    private val articleViewModel: ArticleViewModel by viewModel()
던! 
테스트 해보니까 된당 굿 ㅎ

2020-12-15 07:55 UTC, yoowonyoung commented
@rlarlvy153 니가 체인지 리퀘 걸었어서 너가 approve 해줘야함 이거는

2020-12-20 11:58 UTC, rlarlvy153 approved these changes

2020-12-20 11:58 UTC, merged